ConferenceManagement/ConferenceManagement/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConferenceManagement.Authorize;
using ConferenceManagement.Services.Article;
using ConferenceManagement.Services.Conference;
using ConferenceManagement.Services.User;
using ConferenceManagement.ViewModels.Article;
using ConferenceManagement.ViewModels.Login;

namespace ConferenceManagement.Controllers
{
    [CustomAuthorizeUser(ConferenceManagementRole.Author)]
    public class ArticleController : Controller
    {
        private readonly ArticleManager _articleManager;
        private readonly UserManager _userManager;
        private readonly ConferenceManager _conferenceManager;

        public ArticleController()
        {
            _articleManager = new ArticleManager();
            _userManager = new UserManager();
            _conferenceManager = new ConferenceManager();
        }

        // GET: Article
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProposeArticle()
        {
            var model = new ProposeArticleViewModel();

            var conferences = _conferenceManager.GetConferences().Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });

            model.Conferences = conferences;
            return View(model);
        }

        [HttpPost]
        public ActionResult ProposeArticle(ProposeArticleViewModel model)
        {
            var userId = ((UserSessionModel) Session["user"]).UserId;

            if (model.File.ContentLength > 0)
            {
                var fileName = model.File.FileName;
                var path = AppDomain.CurrentDomain.BaseDirectory + "Documents\\" + fileName;
                model.File.SaveAs(path);
                model.FileName = fileName;
                model.FilePath = path;
            }
            if (!ModelState.IsValid) return RedirectToAction("ListMyArticles");
            var articleId = _articleManager.CreateArticle(model, userId);
            return View("ArticleDetails", _articleManager.GetArticleById(articleId));
        }

        public ActionResult ListMyArticles()
        {
            var currentUserId = ((UserSessionModel) Session["user"]).UserId;
            var model = _articleManager.GetArticlesByUser(currentUserId).ToList();
            return View(model);
        }

        [CustomAuthorizeUser(ConferenceManagementRole.ComiteeMember)]
        public ActionResult ListAllArticles()
        {
            var model = _articleManager.GetAllArticles().ToList();

            return View(model);
        }

        [CustomAuthorizeUser(ConferenceManagementRole.ComiteeMember, ConferenceManagementRole.Author)]
        public ActionResult ArticleDetails(int id)
        {
            var model = _articleManager.GetArticleById(id);
            return View(model);
        }

        [CustomAuthorizeUser(ConferenceManagementRole.ComiteeMember)]
        public ActionResult ReviewArticle(int articleId)
        {
            var article = _articleManager.GetArticleById(articleId);
            var model = new ArticleReviewViewModel
            {
                ArticleId = articleId,
            };

            return View(model);
        }

        [CustomAuthorizeUser(ConferenceManagementRole.ComiteeMember)]
        [HttpPost]
        public ActionResult ReviewArticle(ArticleReviewViewModel articleReview)
        {
            articleReview.ReviewerId = _userManager.GetCommiteeMemberIdByUserId(((UserSessionModel)Session["user"]).UserId);

            _articleManager.AddArticleReview(articleReview);

            return View("ListAllArticles", _articleManager.GetAllArticles());
        }
    }
}

ConferenceManagement/ConferenceManagement/Controllers/ConferenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ConferenceManagement.Authorize;
using ConferenceManagement.Services.Conference;
using ConferenceManagement.ViewModels.Conference;
using ConferenceManagement.ViewModels.Login;

namespace ConferenceManagement.Controllers
{
    [CustomAuthorizeUser(ConferenceManagementRole.Admin)]
    public class ConferenceController : Controller
    {
        private readonly ConferenceManager _conferenceManager;

        public ConferenceController()
        {
            _conferenceManager = new ConferenceManager();
        }

        // GET: Conference
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateConference()
        {
            var model = new CreateConferenceViewModel { Comitees= GetSelectListItems() };

            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreateConference(CreateConferenceViewModel model)
        {
            model.Comitees = GetSelectListItems();
            _conferenceManager.AddConference(model);
            return View("ConferenceAddedSuccessfully");
        }

        [CustomAuthorizeUser(ConferenceManagementRole.ComiteeMember)]
        public ActionResult ListAllConferences()
        {
            var model = new List<ConferenceViewModel>();
            var currentUserId = ((UserSessionModel)Session["user"]).UserId;
            model = User.IsInRole(ConferenceManagementRole.ComiteeMember.ToString()) ? _conferenceManager.GetConferencesByUser(currentUserId).ToList() : _conferenceManager.GetConferences().ToList();
            return View(model);
        }

        [CustomAuthorizeUser(ConferenceManagementRole.ComiteeMember)]
        public ActionResult EditConferences(int id)
        {
            var model = _conferenceManager.GetConferenceById(id);
            return View(model);
        }

        [CustomAuthorizeUser(ConferenceManagementRole.ComiteeMember)]
        [HttpPost]
        public ActionResult EditConferences(ConferenceViewModel model)
        {
            _conferenceManager.UpdateRequest(model);

            return RedirectToAction("ListAllConferences");
        }

        [CustomAuthorizeUser(ConferenceManagementRole.ComiteeMember)]
        public ActionResult ConferenceDetails(int id)
        {
            var model = _conferenceManager.GetConferenceById(id);
            return View(model);
        }

        private IEnumerable<SelectListItem> GetSelectListItems()
        {
            var selectList = new List<SelectListItem>
            {
                new SelectListItem{
                    Value = ((int)ConferenceManagementComitee.Comitee1).ToString(),
                    Text = ConferenceManagementComitee.Comitee1.ToString()
                },
                new SelectListItem{
                    Value = ((int)ConferenceManagementComitee.Comitee2).ToString(),
                    Text = ConferenceManagementComitee.Comitee2.ToString()
                },
                new SelectListItem{
                    Value = ((int)ConferenceManagementComitee.Comitee3).ToString(),
                    Text = ConferenceManagementComitee.Comitee3.ToString()
                },
                new SelectListItem{
                    Value = ((int)ConferenceManagementComitee.Comitee4).ToString(),
                    Text = ConferenceManagementComitee.Comitee4.ToString()
                }
            };
            return selectList;
        }
    }
}

ConferenceManagement/ConferenceManagement/Controllers/UserController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using ConferenceManagement.Authorize;
using ConferenceManagement.Services.User;
using ConferenceManagement.ViewModels.Conference;
using ConferenceManagement.ViewModels.Login;
using ConferenceManagement.ViewModels.User;

namespace ConferenceManagement.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager _userManager;

        public UserController()
        {
            _userManager = new UserManager();
        }
        
        public ActionResult CreateAuthor()
        {
            var model = new CreateUserViewModel { };
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAuthor(CreateUserViewModel model)
        {
            _userManager.AddAuthorUser(model);
            return View();
        }

        [CustomAuthorizeUser(ConferenceManagementRole.Admin)]
        public ActionResult CreateComiteeMember()
        {
            var model = new CreateUserViewModel { Comitees = GetSelectListItems()};
            return View(model);
        }

        [HttpPost]
        [CustomAuthorizeUser(ConferenceManagementRole.Admin)]
        [ValidateAntiForgeryToken]
        public ActionResult CreateComiteeMember(CreateUserViewModel model)
        {
            _userManager.AddComiteeMemberUser(model);
            return View("AccountCreatedSuccessfully");
        }

        private IEnumerable<SelectListItem> GetSelectListItems()
        {
            var selectList = new List<SelectListItem>
            {
                new SelectListItem{
                    Value = ((int)ConferenceManagementComitee.Comitee1).ToString(),
                    Text = ConferenceManagementComitee.Comitee1.ToString()
                },
                new SelectListItem{
                    Value = ((int)ConferenceManagementComitee.Comitee2).ToString(),
                    Text = ConferenceManagementComitee.Comitee2.ToString()
                },
                new SelectListItem{
                    Value = ((int)ConferenceManagementComitee.Comitee3).ToString(),
                    Text = ConferenceManagementComitee.Comitee3.ToString()
                },
                new SelectListItem{
                    Value = ((int)ConferenceManagementComitee.Comitee4).ToString(),
                    Text = ConferenceManagementComitee.Comitee4.ToString()
                }
            };
            return selectList;
        }

    }
}

ConferenceManagement/ConferenceManagement/Views/Shared/_Layout.cshtml
@using ConferenceManagement.ViewModels.Login
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Conference Management App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                <ul class="nav navbar-nav navbar-left">
                    @if (User.IsInRole(ConferenceManagementRole.Admin.ToString()))
                    {
                        <li>@Html.ActionLink("Create Account", "CreateComiteeMember", "User")</li>
                        <li>@Html.ActionLink("Create Conference", "CreateConference", "Conference")</li>
                    }
                    @if (User.IsInRole(ConferenceManagementRole.ComiteeMember.ToString()))
                    {
                        <li>@Html.ActionLink("See conferences", "ListAllConferences", "Conference")</li>
                    }
                    @if (User.IsInRole(ConferenceManagementRole.ComiteeMember.ToString()))
                    {
                        <li>@Html.ActionLink("Articles", "ListAllArticles", "Article")</li>
                    }
                    @if (User.IsInRole(ConferenceManagementRole.Author.ToString()))
                    {
                        <li>@Html.ActionLink("My Articles", "ListMyArticles", "Article")</li>
                        <li>@Html.ActionLink("Propose Article", "ProposeArticle", "Article")</li>
                    }
                </ul>
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tatooine</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>